[package]
name = "starterprototype"
version = "0.1.0"
authors = ["vblz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winreg = "0.7"
toml = "0.5"
serde_derive = "1.0"
serde = "1.0"